# Generated by Django 5.2.3 on 2025-06-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitudo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moradia',
            name='contato',
            field=models.CharField(max_length=255, verbose_name='Contato para Moradia (Tel, Email, Insta)'),
        ),
    ]
