# Generated by Django 5.2.3 on 2025-06-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitudo', '0002_alter_moradia_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carona',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='moradia',
            name='contato',
        ),
        migrations.AddField(
            model_name='carona',
            name='tipo_contato',
            field=models.CharField(choices=[('TELEFONE', 'Telefone/WhatsApp'), ('EMAIL', 'E-mail'), ('INSTAGRAM', 'Instagram'), ('OUTRO', 'Outro')], default='TELEFONE', max_length=20, verbose_name='Tipo de Contato'),
        ),
        migrations.AddField(
            model_name='carona',
            name='valor_contato',
            field=models.CharField(default='TELEFONE', max_length=255, verbose_name='Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moradia',
            name='tipo_contato',
            field=models.CharField(choices=[('TELEFONE', 'Telefone/WhatsApp'), ('EMAIL', 'E-mail'), ('INSTAGRAM', 'Instagram'), ('OUTRO', 'Outro')], default='TELEFONE', max_length=20, verbose_name='Tipo de Contato'),
        ),
        migrations.AddField(
            model_name='moradia',
            name='valor_contato',
            field=models.CharField(default='', max_length=255, verbose_name='Contato'),
            preserve_default=False,
        ),
    ]
