# Generated by Django 5.2.3 on 2025-06-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitudo', '0003_remove_carona_contato_remove_moradia_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome Completo'),
        ),
    ]
