# .github/workflows/main_unitudo.yml (ou o nome do seu arquivo)

name: Build and deploy Python app to Azure Web App - unitudo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read   # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C18095BB81F14870A6E21FB010A0F205 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8D3E3CE6BC354DF5B17B85249B6FA29A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BA3CEADA19A342D18D99BB37313DAE9F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'unitudo'
          slot-name: 'Production'
